LPS-167069 | Add test UserFieldsAbleToExportToLDAP
nikki-pru/liferay-portal pull request #851
Opened 2023-06-27 08:18 UTC by bronsonsoda

https://liferay.atlassian.net/browse/LPS-167069

2023-06-27 08:18 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2023-06-27 08:18 UTC, bronsonsoda commented
ci:test:relevant

2023-06-27 08:19 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>relevant</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest(master)/5662/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-39.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/5662/jenkins-report.html">here</a>.</b></p>

2023-06-28 16:40 UTC, nikki-pru requested changes

2023-08-24 16:33 UTC, nikki-pru commented
ci:test:sf

2023-08-24 16:37 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-7.liferay.com/job/test-portal-source-format/5392/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-7.liferay.com/userContent/jobs/test-portal-source-format/builds/5392/jenkins-report.html">here</a>.</b></p>

2023-08-24 16:45 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-7.liferay.com/job/test-portal-source-format/5392/">test-portal-source-format#5392</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-7.liferay.com/userContent/jobs/test-portal-source-format/builds/5392/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/nikki-pru/liferay-portal/pull/851">nikki-pru#851</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2412135866">[master] ci:test:sf - bronsonsoda &gt; nikki-pru - PR#851 - 2023-08-24[09:33:44]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-7.liferay.com/job/publish-testray-report/3210/">publish-testray-report#3210</a><br/></div></div>

2024-01-23 05:08 UTC, closed without merging